#!/usr/bin/env python3
"""Generate reverse-pin-order ("mirrored") variants of the two panel FPC footprints.

The panel's tails arrive with their pin 1 at the *top*, but the connector as drawn
has pin 1 at the bottom, so the cable's conductor 1 physically touches the
connector's last contact.  The library's own convention for this is a `_Mirrored`
land pattern: **the numbered pads are mirrored in X, the mechanical pad and the
body are not**, so the same physical part is soldered in the same orientation and
only the pad numbering runs the other way.  See the existing
`Xunpu_FPC-05F-8PH20_..._Horizontal_Mirrored` in `pcb_common`.

Doing it here rather than by renumbering the schematic keeps `J6`/`J24` matching
the panel datasheet, `pcb/40p-adapter-ab` and `epd-port.md` §9.5 pin-for-pin.

Output goes to the project-local `r2.pretty`, not the `pcb_common` submodule.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
OUT = HERE / "r2.pretty"
SRC = {
    "HC-FPC-05-09-8RLTAG":
        HERE.parent / "pcb_common/footprints.pretty/HC-FPC-05-09-8RLTAG.kicad_mod",
    "Omron_XF2M-4015-1A_1x40-1MP_P0.5mm_Horizontal":
        Path("/home/lum/Apps/kicad-10.0.4/usr/share/kicad/footprints/Connector_FFC-FPC.pretty"
             "/Omron_XF2M-4015-1A_1x40-1MP_P0.5mm_Horizontal.kicad_mod"),
}


def fmt(v):
    s = f"{v:.6f}".rstrip("0").rstrip(".")
    return s if s not in ("", "-0") else "0"


def mirror(text, name):
    """Mirror every graphic and every *numbered* pad in X; leave MP and text alone."""
    out, i, npads, ngfx = [], 0, 0, 0
    # graphics: (start x y) (end x y) (center ...) (mid ...) (xy ...)
    def flip_pt(m):
        nonlocal ngfx
        ngfx += 1
        return f"({m.group(1)} {fmt(-float(m.group(2)))} {m.group(3)})"

    # split pads out first so we can treat MP differently
    chunks, pos = [], 0
    for pm in re.finditer(r'\t\(pad "([^"]+)"', text):
        s = pm.start()
        depth, k = 0, s
        while k < len(text):
            if text[k] == "(":
                depth += 1
            elif text[k] == ")":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        chunks.append((pos, s, None))
        chunks.append((s, k + 1, pm.group(1)))
        pos = k + 1
    chunks.append((pos, len(text), None))

    for a, b, padnum in chunks:
        seg = text[a:b]
        if padnum is None:
            seg = re.sub(r'\((start|end|center|mid) ([\d.-]+) ([\d.-]+)\)', flip_pt, seg)
            seg = re.sub(r'\(xy ([\d.-]+) ([\d.-]+)\)',
                         lambda m: f"(xy {fmt(-float(m.group(1)))} {m.group(2)})", seg)
        elif padnum.isdigit():
            npads += 1
            seg = re.sub(r'\(at ([\d.-]+) ([\d.-]+)( [\d.-]+)?\)',
                         lambda m: f"(at {fmt(-float(m.group(1)))} {m.group(2)}{m.group(3) or ''})",
                         seg, count=1)
        out.append(seg)

    t = "".join(out)
    t = t.replace(f'(footprint "{name}"', f'(footprint "{name}_Mirrored"', 1)
    d = re.search(r'\(descr "([^"]*)"\)', t)
    if d:
        t = t.replace(d.group(0),
                      f'(descr "{d.group(1)} -- MIRRORED: pad numbering reversed end-for-end, '
                      f'body and mounting pad unchanged. Generated by tools/gen_mirrored_fpc.py")', 1)
    return t, npads, ngfx


def main():
    OUT.mkdir(exist_ok=True)
    for name, src in SRC.items():
        if not src.exists():
            sys.exit(f"source footprint missing: {src}")
        text = src.read_text(encoding="utf-8")
        t, npads, ngfx = mirror(text, name)
        dst = OUT / f"{name}_Mirrored.kicad_mod"
        dst.write_text(t, encoding="utf-8")
        # verify: pad 1 and pad N swapped ends, MP unmoved
        def pads(s):
            out = {}
            for pm in re.finditer(r'\(pad "([^"]+)"', s):
                a = s.find("(at ", pm.end())
                m = re.match(r'\(at ([\d.-]+) ([\d.-]+)', s[a:a + 40])
                out[pm.group(1)] = (float(m.group(1)), float(m.group(2)))
            return out
        p0, p1 = pads(text), pads(t)
        nums = sorted([k for k in p0 if k.isdigit()], key=int)
        lo, hi = nums[0], nums[-1]
        assert abs(p1[lo][0] - p0[hi][0]) < 1e-6, f"{name}: pad {lo} did not land on pad {hi}'s x"
        assert p1["MP"] == p0["MP"], f"{name}: MP moved"
        print(f"{dst.name}: {npads} pads mirrored, {ngfx} graphic points mirrored")
        print(f"    pad {lo}: {p0[lo][0]:+.3f} -> {p1[lo][0]:+.3f}   "
              f"pad {hi}: {p0[hi][0]:+.3f} -> {p1[hi][0]:+.3f}   MP {p1['MP']} unchanged")


if __name__ == "__main__":
    main()
